# GENERATED BY NifGram. DO NOT EDIT!
# ORIGINAL FILE: src/nifc/amd64/asm_grammar.nif
proc genInstruction(c: var Context): bool



proc genDirective(c: var Context): bool =
  when declared(handleDirective):
    var before1 = save(c)
  var kw2 = false
  if isTag(c, GlobalT):
    emitTag(c, "global")
    if not lookupSym(c):
      error(c, "SYMBOL expected")
      return false
    nl(c)
    kw2 = matchParRi(c)
  if not kw2: return false
  when declared(handleDirective):
    handleDirective(c, before1)
  return true

proc genCode(c: var Context): bool =
  when declared(handleCode):
    var before1 = save(c)
  var kw2 = false
  if isTag(c, TextT):
    emitTag(c, "text")
    var sym3 = declareSym(c)
    if not success(sym3):
      error(c, "SYMBOLDEF expected")
      return false
    var om4 = false
    while not peekParRi(c):
      if not genInstruction(c):
        break
      else:
        om4 = true
    if not om4:
      error(c, "invalid Code")
      return false
    kw2 = matchParRi(c)
  if not kw2: return false
  when declared(handleCode):
    handleCode(c, before1)
  return true

proc genExternDecl(c: var Context): bool =
  when declared(handleExternDecl):
    var before1 = save(c)
  var kw2 = false
  if isTag(c, ExternT):
    emitTag(c, "extern")
    var sym3 = declareSym(c)
    if not success(sym3):
      error(c, "SYMBOLDEF expected")
      return false
    nl(c)
    kw2 = matchParRi(c)
  if not kw2: return false
  when declared(handleExternDecl):
    handleExternDecl(c, before1)
  return true

proc genDataValue(c: var Context): bool =
  when declared(handleDataValue):
    var before1 = save(c)
  var or2 = false
  block or3:
    if matchStringLit(c):
      or2 = true
      break or3
    if matchIntLit(c):
      or2 = true
      break or3
    if matchUIntLit(c):
      or2 = true
      break or3
    if matchFloatLit(c):
      or2 = true
      break or3
  if not or2: return false
  when declared(handleDataValue):
    handleDataValue(c, before1)
  return true

proc genTimes(c: var Context): bool =
  when declared(handleTimes):
    var before1 = save(c)
  var or2 = false
  block or3:
    if genDataValue(c):
      or2 = true
      break or3
    var kw4 = false
    if isTag(c, TimesT):
      emitTag(c, "times")
      if not matchIntLit(c):
        error(c, "INTLIT expected")
        break or3
      if not genDataValue(c):
        error(c, "DataValue expected")
        break or3
      kw4 = matchParRi(c)
    if kw4:
      or2 = true
      break or3
  if not or2: return false
  when declared(handleTimes):
    handleTimes(c, before1)
  return true

proc genTimes2(c: var Context): bool =
  when declared(handleTimes2):
    var before1 = save(c)
  emit(c, ", ")
  
  if not genTimes(c): return false
  when declared(handleTimes2):
    handleTimes2(c, before1)
  return true

proc genDataKey(c: var Context): bool =
  when declared(handleDataKey):
    var before1 = save(c)
  var sym2 = declareSym(c)
  if not success(sym2): return false
  if not genTimes(c): return false
  var zm3 = true
  while not peekParRi(c):
    if not genTimes2(c):
      zm3 = false
      break
  if not zm3: return false
  when declared(handleDataKey):
    handleDataKey(c, before1)
  return true

proc genDataDecl(c: var Context): bool =
  when declared(handleDataDecl):
    var before1 = save(c)
  var or2 = false
  block or3:
    var kw4 = false
    if isTag(c, DbT):
      emitTag(c, "db")
      if not genDataKey(c):
        error(c, "DataKey expected")
        break or3
      kw4 = matchParRi(c)
    if kw4:
      or2 = true
      break or3
    var kw5 = false
    if isTag(c, DwT):
      emitTag(c, "dw")
      if not genDataKey(c):
        error(c, "DataKey expected")
        break or3
      kw5 = matchParRi(c)
    if kw5:
      or2 = true
      break or3
    var kw6 = false
    if isTag(c, DdT):
      emitTag(c, "dd")
      if not genDataKey(c):
        error(c, "DataKey expected")
        break or3
      kw6 = matchParRi(c)
    if kw6:
      or2 = true
      break or3
    var kw7 = false
    if isTag(c, DqT):
      emitTag(c, "dq")
      if not genDataKey(c):
        error(c, "DataKey expected")
        break or3
      kw7 = matchParRi(c)
    if kw7:
      or2 = true
      break or3
  if not or2: return false
  nl(c)
  
  when declared(handleDataDecl):
    handleDataDecl(c, before1)
  return true

proc genData(c: var Context): bool =
  when declared(handleData):
    var before1 = save(c)
  var kw2 = false
  if isTag(c, DataT):
    emitTag(c, "data")
    var zm3 = true
    while not peekParRi(c):
      if not genDataDecl(c):
        zm3 = false
        break
    if not zm3:
      error(c, "invalid Data")
      return false
    kw2 = matchParRi(c)
  if not kw2: return false
  nl(c)
  
  when declared(handleData):
    handleData(c, before1)
  return true

proc genRodata(c: var Context): bool =
  when declared(handleRodata):
    var before1 = save(c)
  var kw2 = false
  if isTag(c, RodataT):
    emitTag(c, "rodata")
    var zm3 = true
    while not peekParRi(c):
      if not genDataDecl(c):
        zm3 = false
        break
    if not zm3:
      error(c, "invalid Rodata")
      return false
    kw2 = matchParRi(c)
  if not kw2: return false
  nl(c)
  
  when declared(handleRodata):
    handleRodata(c, before1)
  return true

proc genSection(c: var Context): bool =
  when declared(handleSection):
    var before1 = save(c)
  var or2 = false
  block or3:
    if genDirective(c):
      or2 = true
      break or3
    if genExternDecl(c):
      or2 = true
      break or3
    if genCode(c):
      or2 = true
      break or3
    if genData(c):
      or2 = true
      break or3
    if genRodata(c):
      or2 = true
      break or3
  if not or2: return false
  when declared(handleSection):
    handleSection(c, before1)
  return true

proc genModule(c: var Context): bool =
  when declared(handleModule):
    var before1 = save(c)
  var kw2 = false
  if isTag(c, StmtsT):
    emitTag(c, "stmts")
    var zm3 = true
    while not peekParRi(c):
      if not genSection(c):
        zm3 = false
        break
    if not zm3:
      error(c, "invalid Module")
      return false
    kw2 = matchParRi(c)
  if not kw2: return false
  when declared(handleModule):
    handleModule(c, before1)
  return true

proc genReg(c: var Context): bool =
  when declared(handleReg):
    var before1 = save(c)
  var or2 = false
  block or3:
    if matchAndEmitTag(c, RaxT, "rax"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RbxT, "rbx"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RcxT, "rcx"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RdxT, "rdx"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RsiT, "rsi"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RdiT, "rdi"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RbpT, "rbp"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RspT, "rsp"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R8T, "r8"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R9T, "r9"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R10T, "r10"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R11T, "r11"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R12T, "r12"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R13T, "r13"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R14T, "r14"):
      or2 = true
      break or3
    if matchAndEmitTag(c, R15T, "r15"):
      or2 = true
      break or3
  if not or2: return false
  when declared(handleReg):
    handleReg(c, before1)
  return true

proc genFpReg(c: var Context): bool =
  when declared(handleFpReg):
    var before1 = save(c)
  var or2 = false
  block or3:
    if matchAndEmitTag(c, Xmm0T, "xmm0"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm1T, "xmm1"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm2T, "xmm2"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm3T, "xmm3"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm4T, "xmm4"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm6T, "xmm6"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm7T, "xmm7"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm8T, "xmm8"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm9T, "xmm9"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm10T, "xmm10"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm11T, "xmm11"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm12T, "xmm12"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm13T, "xmm13"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm14T, "xmm14"):
      or2 = true
      break or3
    if matchAndEmitTag(c, Xmm15T, "xmm15"):
      or2 = true
      break or3
  if not or2: return false
  when declared(handleFpReg):
    handleFpReg(c, before1)
  return true

proc genPrimary(c: var Context): bool =
  when declared(handlePrimary):
    var before1 = save(c)
  var or2 = false
  block or3:
    if genReg(c):
      or2 = true
      break or3
    if genFpReg(c):
      or2 = true
      break or3
    if lookupSym(c):
      or2 = true
      break or3
    var kw4 = false
    if isTag(c, RelT):
      emitTag(c, "rel")
      if not lookupSym(c):
        error(c, "SYMBOL expected")
        break or3
      kw4 = matchParRi(c)
    if kw4:
      or2 = true
      break or3
    var kw5 = false
    if isTag(c, FsT):
      emit(c, "fs:[")
      if not lookupSym(c):
        error(c, "SYMBOL expected")
        break or3
      emit(c, "@TPOFF]")
      kw5 = matchParRi(c)
    if kw5:
      or2 = true
      break or3
    if matchIntLit(c):
      or2 = true
      break or3
    if matchUIntLit(c):
      or2 = true
      break or3
  if not or2: return false
  when declared(handlePrimary):
    handlePrimary(c, before1)
  return true

proc genExpr(c: var Context): bool =
  when declared(handleExpr):
    var before1 = save(c)
  var or2 = false
  block or3:
    if genPrimary(c):
      or2 = true
      break or3
    var kw4 = false
    if isTag(c, Mem1T):
      emit(c, "[")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      emit(c, "]")
      kw4 = matchParRi(c)
    if kw4:
      or2 = true
      break or3
    var kw5 = false
    if isTag(c, Mem2T):
      emit(c, "[")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      emit(c, "+")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      emit(c, "]")
      kw5 = matchParRi(c)
    if kw5:
      or2 = true
      break or3
    var kw6 = false
    if isTag(c, Mem3T):
      emit(c, "[")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      emit(c, "+")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      emit(c, "*")
      if not matchIntLit(c):
        error(c, "INTLIT expected")
        break or3
      emit(c, "]")
      kw6 = matchParRi(c)
    if kw6:
      or2 = true
      break or3
    var kw7 = false
    if isTag(c, Mem4T):
      emit(c, "[")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      emit(c, "+")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      emit(c, "*")
      if not matchIntLit(c):
        error(c, "INTLIT expected")
        break or3
      emit(c, "+")
      if not matchIntLit(c):
        error(c, "INTLIT expected")
        break or3
      emit(c, "]")
      kw7 = matchParRi(c)
    if kw7:
      or2 = true
      break or3
    var kw8 = false
    if isTag(c, ByteatT):
      emit(c, "BYTE PTR ")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      kw8 = matchParRi(c)
    if kw8:
      or2 = true
      break or3
    var kw9 = false
    if isTag(c, WordatT):
      emit(c, "WORD PTR ")
      if not genPrimary(c):
        error(c, "Primary expected")
        break or3
      kw9 = matchParRi(c)
    if kw9:
      or2 = true
      break or3
  if not or2: return false
  when declared(handleExpr):
    handleExpr(c, before1)
  return true

proc genLabel(c: var Context): bool =
  when declared(handleLabel):
    var before1 = save(c)
  if not lookupSym(c): return false
  when declared(handleLabel):
    handleLabel(c, before1)
  return true

proc genInstruction(c: var Context): bool =
  when declared(handleInstruction):
    var before1 = save(c)
  var or2 = false
  block or3:
    var kw4 = false
    if isTag(c, MovT):
      emitTag(c, "mov")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw4 = matchParRi(c)
    if kw4:
      or2 = true
      break or3
    var kw5 = false
    if isTag(c, MovapdT):
      emitTag(c, "movapd")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw5 = matchParRi(c)
    if kw5:
      or2 = true
      break or3
    var kw6 = false
    if isTag(c, MovsdT):
      emitTag(c, "movsd")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw6 = matchParRi(c)
    if kw6:
      or2 = true
      break or3
    var kw7 = false
    if isTag(c, LeaT):
      emitTag(c, "lea")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw7 = matchParRi(c)
    if kw7:
      or2 = true
      break or3
    var kw8 = false
    if isTag(c, AddT):
      emitTag(c, "add")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw8 = matchParRi(c)
    if kw8:
      or2 = true
      break or3
    var kw9 = false
    if isTag(c, SubT):
      emitTag(c, "sub")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw9 = matchParRi(c)
    if kw9:
      or2 = true
      break or3
    var kw10 = false
    if isTag(c, MulT):
      emitTag(c, "mul")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw10 = matchParRi(c)
    if kw10:
      or2 = true
      break or3
    var kw11 = false
    if isTag(c, ImulT):
      emitTag(c, "imul")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw11 = matchParRi(c)
    if kw11:
      or2 = true
      break or3
    var kw12 = false
    if isTag(c, DivT):
      emitTag(c, "div")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw12 = matchParRi(c)
    if kw12:
      or2 = true
      break or3
    var kw13 = false
    if isTag(c, IdivT):
      emitTag(c, "idiv")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw13 = matchParRi(c)
    if kw13:
      or2 = true
      break or3
    var kw14 = false
    if isTag(c, XorT):
      emitTag(c, "xor")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw14 = matchParRi(c)
    if kw14:
      or2 = true
      break or3
    var kw15 = false
    if isTag(c, AddsdT):
      emitTag(c, "addsd")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw15 = matchParRi(c)
    if kw15:
      or2 = true
      break or3
    var kw16 = false
    if isTag(c, SubsdT):
      emitTag(c, "subsd")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw16 = matchParRi(c)
    if kw16:
      or2 = true
      break or3
    var kw17 = false
    if isTag(c, MulsdT):
      emitTag(c, "mulsd")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw17 = matchParRi(c)
    if kw17:
      or2 = true
      break or3
    var kw18 = false
    if isTag(c, DivsdT):
      emitTag(c, "divsd")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw18 = matchParRi(c)
    if kw18:
      or2 = true
      break or3
    var kw19 = false
    if isTag(c, PushT):
      emitTag(c, "push")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw19 = matchParRi(c)
    if kw19:
      or2 = true
      break or3
    var kw20 = false
    if isTag(c, PopT):
      emitTag(c, "pop")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw20 = matchParRi(c)
    if kw20:
      or2 = true
      break or3
    var kw21 = false
    if isTag(c, IncT):
      emitTag(c, "inc")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw21 = matchParRi(c)
    if kw21:
      or2 = true
      break or3
    var kw22 = false
    if isTag(c, DecT):
      emitTag(c, "dec")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw22 = matchParRi(c)
    if kw22:
      or2 = true
      break or3
    var kw23 = false
    if isTag(c, NegT):
      emitTag(c, "neg")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw23 = matchParRi(c)
    if kw23:
      or2 = true
      break or3
    var kw24 = false
    if isTag(c, CmpT):
      emitTag(c, "cmp")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw24 = matchParRi(c)
    if kw24:
      or2 = true
      break or3
    var kw25 = false
    if isTag(c, TestT):
      emitTag(c, "test")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      emit(c, ", ")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw25 = matchParRi(c)
    if kw25:
      or2 = true
      break or3
    var kw26 = false
    if isTag(c, CallT):
      emitTag(c, "call")
      if not genExpr(c):
        error(c, "Expr expected")
        break or3
      kw26 = matchParRi(c)
    if kw26:
      or2 = true
      break or3
    var kw27 = false
    if isTag(c, LabT):
      emitTag(c, "lab")
      var sym28 = declareSym(c)
      if not success(sym28):
        error(c, "SYMBOLDEF expected")
        break or3
      kw27 = matchParRi(c)
    if kw27:
      or2 = true
      break or3
    var kw29 = false
    if isTag(c, JmpT):
      emitTag(c, "jmp")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw29 = matchParRi(c)
    if kw29:
      or2 = true
      break or3
    var kw30 = false
    if isTag(c, JeT):
      emitTag(c, "je")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw30 = matchParRi(c)
    if kw30:
      or2 = true
      break or3
    var kw31 = false
    if isTag(c, JneT):
      emitTag(c, "jne")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw31 = matchParRi(c)
    if kw31:
      or2 = true
      break or3
    var kw32 = false
    if isTag(c, JzT):
      emitTag(c, "jz")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw32 = matchParRi(c)
    if kw32:
      or2 = true
      break or3
    var kw33 = false
    if isTag(c, JnzT):
      emitTag(c, "jnz")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw33 = matchParRi(c)
    if kw33:
      or2 = true
      break or3
    var kw34 = false
    if isTag(c, JgT):
      emitTag(c, "jg")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw34 = matchParRi(c)
    if kw34:
      or2 = true
      break or3
    var kw35 = false
    if isTag(c, JgeT):
      emitTag(c, "jge")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw35 = matchParRi(c)
    if kw35:
      or2 = true
      break or3
    var kw36 = false
    if isTag(c, JaT):
      emitTag(c, "ja")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw36 = matchParRi(c)
    if kw36:
      or2 = true
      break or3
    var kw37 = false
    if isTag(c, JaeT):
      emitTag(c, "jae")
      if not genLabel(c):
        error(c, "Label expected")
        break or3
      kw37 = matchParRi(c)
    if kw37:
      or2 = true
      break or3
    if matchAndEmitTag(c, NopT, "nop"):
      or2 = true
      break or3
    if matchAndEmitTag(c, RetT, "ret"):
      or2 = true
      break or3
    if matchAndEmitTag(c, SyscallT, "syscall"):
      or2 = true
      break or3
    var kw38 = false
    if isTag(c, CommentT):
      emit(c, "; ")
      var or39 = false
      block or40:
        if matchIdent(c):
          or39 = true
          break or40
        if lookupSym(c):
          or39 = true
          break or40
        if matchStringLit(c):
          or39 = true
          break or40
      if not or39:
        error(c, "invalid Instruction")
        break or3
      kw38 = matchParRi(c)
    if kw38:
      or2 = true
      break or3
  if not or2: return false
  nl(c)
  
  when declared(handleInstruction):
    handleInstruction(c, before1)
  return true
